# 国内镜像加速
REG_MIRROR_1: "https://registry.docker-cn.com"
REG_MIRROR_2: "https://docker.mirrors.ustc.edu.cn"

# 非安全的仓库
INSECURE_MIRROR: "docker-test-virtual.repo.yrd.creditease.corp","lend-docker-test-local.repo.yrd.creditease.corp"

# docker日志相关
LOG_DRIVER: "json-file"
LOG_LEVEL: "warn"
LOG_MAX_SIZE: "10m"
LOG_MAX_FILE: 3

# docker容器存储目录
STORAGE_DIR: "/var/lib/docker"
