---
- name: 下载证书工具 cfssl
  get_url:
    url: https://pkg.cfssl.org/{{cfssl_version}}/cfssl_linux-amd64
    dest: "{{bin_dir}}/cfssl"
    mode: 0755

- name: 下载证书工具  cfssljson
  get_url:
    url: https://pkg.cfssl.org/{{cfssl_version}}/cfssljson_linux-amd64
    dest: "{{bin_dir}}/cfssljson"
    mode: 0755

- name: 下载证书工具  cfssl-certinfo
  get_url:
    url: https://pkg.cfssl.org/{{cfssl_version}}/cfssl-certinfo_linux-amd64
    dest: "{{bin_dir}}/cfssl-certinfo"
    mode: 0755