---
# to create CA, kubeconfig, kube-proxy.kubeconfig etc. on 'deploy' node
- hosts: deploy
  roles:
  - deploy

# prepare tasks for all nodes
- hosts: all
  roles:
  - prepare

# 安装 loadbalance
- hosts: lb
  roles:
  - lb

# 安装 etcd 集群
- hosts: etcd
  roles:
  - etcd

# 安装 docker
- hosts:
  - kube-master
  - kube-node
  roles:
  - docker

# 安装 kubernetes 节点
- hosts: kube-master
  roles:
  - kube-master
  - kube-node

  tasks:
  - name: Making master nodes SchedulingDisabled
    shell: "{{ bin_dir }}/kubectl cordon {{ inventory_hostname }} "
    delegate_to: "{{ groups.deploy[0] }}"
    when: DEPLOY_MODE != "allinone"
    ignore_errors: true

  - name: Setting master role name
    shell: "{{ bin_dir }}/kubectl label node {{ inventory_hostname }} kubernetes.io/role=master --overwrite"
    ignore_errors: true
    delegate_to: "{{ groups.deploy[0] }}"

# 安装网络插件
- hosts:
  - kube-master
  - kube-node
  roles:
  - role: calico

# 安装 clust-addons
- hosts:
  - kube-node
  roles:
  - cluster-addon
